services:

  # Proxy

  proxy:
    image: traefik:v3.7
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - 80:80
    depends_on:
      - client
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Database

  db:
    build: ./database
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_pw_admin
      POSTGRES_DB: kochbuch
    secrets:
      - pg_pw_admin
      - kochbuch_pw_admin
    volumes:
      - postgres_data:/var/lib/postgresql

  # Backend

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: production
    restart: unless-stopped
    environment:
      CHOKIDAR_USEPOLLING: true
      DATABASE_HOST: db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_DB: kochbuch
      HOSTNAME: ${HOSTNAME:?}
      PORT: 5001
      MODE: prod
    secrets:
      - pg_pw_admin
      - session_secret
    volumes:
      - uploads:/app/uploads
    depends_on:
      - db
    labels:
      traefik.http.routers.backend.rule: Host(`${HOSTNAME:?}`) && PathPrefix(`/api`)
      traefik.http.routers.backend.middlewares: "backend-stripprefix"
      traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes: "/api"
      traefik.http.services.backend.loadbalancer.server.port: 5001

  # Client

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
      target: production
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      CHOKIDAR_USEPOLLING: true
      HOSTNAME: ${HOSTNAME:?}
      MODE: prod
    labels:
      traefik.http.routers.client.rule: "Host(`${HOSTNAME:?}`)"
      traefik.http.services.client.loadbalancer.server.port: 5173

secrets:
  pg_pw_admin:
    file: ./secrets/pg_pw_admin
  kochbuch_pw_admin:
    file: ./secrets/kochbuch_pw_admin
  session_secret:
    file: ./secrets/session_secret

volumes:
  postgres_data:
  uploads:
