services:

  # Proxy

  proxy:
    command:
      - --api.insecure=true

      - --providers.docker=true
      - --providers.docker.exposedbydefault=false

      - --entrypoints.web.address=:80
    ports:
      - ${HTTP_PORT:-80}:80
      - 8080:8080

  # Backend

  backend:
    build:
      target: development
    develop:
      watch:
        - path: ./backend
          action: sync+restart
          target: /app/backend
        - path: ./common
          action: rebuild
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/tsconfig.json
          action: rebuild
    environment:
      MODE: dev

  # Client

  client:
    build:
      target: development
    develop:
      watch:
        - path: ./client
          action: sync
          target: /app/client
        - path: ./common
          action: rebuild
        - path: ./client/package.json
          action: rebuild
    environment:
      MODE: dev
    volumes:
      - uploads:/app/client/public/uploads:ro
    labels:
      traefik.http.services.client.loadbalancer.server.port: 5173

  # pgAdmin

  pgadmin:
    image: elestio/pgadmin:latest
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=login@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=5004
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    labels:
      traefik.enable: true
      traefik.http.routers.pgadmin.entrypoints: web
      traefik.http.routers.pgadmin.rule: Host(`db.${HOSTNAME:?}`)
      traefik.http.services.pgadmin.loadbalancer.server.port: 5004

volumes:
  pgadmin_data:
