services:

  # Proxy

  proxy:
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false

      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443

      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL:?}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt

  # Backend

  backend:
    labels:
      traefik.http.routers.backend.entrypoints: websecure
      traefik.http.routers.backend.tls: true
      traefik.http.routers.backend.tls.certresolver: letsencrypt

  # Client

  client:
    labels:
      traefik.http.routers.client.entrypoints: websecure
      traefik.http.routers.client.tls: true
      traefik.http.routers.client.tls.certresolver: letsencrypt
